### ISSUE TITLE
Random entity spawn

### ISSUE THREAD

**Issue by tyler72us** [LightBlueGamer/Lithereal_1.19#2]
I recently updated and a small mite like create keeps spawning randomly regardless of my location.  The entity is named "entity.lithereal.moscer".  They jump around a lot so it is annoying to hit them but they spawn in my base so I can't get away from them.

**Comment by LightBlueGamer** [comment]
Is this on the fabric or forge version of the mod, I should be able to send out a patch later today fixing this.

**Comment by tyler72us** [comment]
It the version found in [LiteCraft [FORGE] V12 1.19](https://www.curseforge.com/minecraft/modpacks/the-litecraft-pack/files/4257993).  I noticed you are the author of the mod pack too so I figured I would send you right to the source.

**Comment by LightBlueGamer** [comment]
I'll make sure to locate and patch the bug layer today, the modpack however is waiting for some more stability to forge so it won't be updated in the pack but you'll be able to update the mod in the pack manually

**Comment by tyler72us** [comment]
Ok this may be a Noob question, but how do I update individual mods in curse forge?  I could put the new file in the mod folder but wouldn't curse forge try to "update" and restore the previous version?

**Comment by LightBlueGamer** [comment]
Profile options > enable content management, updating mods folder might work too

**Comment by tyler72us** [comment]
That's perfect. Thanks! Let me know when you think it's fixed.

**Comment by LightBlueGamer** [comment]
Issue should be resolved, it was a problem with the code using spawn rules of any light level monster isntead of just low light/no light. Heres the link to the [patch](https://www.curseforge.com/minecraft/mc-mods/lithereal/files/4375579), if problem still occurs after the update feel free to dm me on discord @Tim_#6397 or open a new issue here.
